_BASE_: "../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "/Path/to/ImageNet/Pretrain/Weight"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
  ROI_HEADS:
    NUM_CLASSES: 55
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.75
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_CONV: 0
    CONV_DIM: 256
    NUM_FC: 2
    FC_DIM: 1024
    NORM: ""
DATASETS:
  TRAIN: ('paco_train_base',)
  TEST: ('paco_test_base',)
SOLVER:
  IMS_PER_BATCH: 16
  STEPS: (70000, 80000)
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 10000
OUTPUT_DIR: "/Path/to/Output/Dir"